### ISSUE TITLE
Are you seriously depend on master branch?

### ISSUE THREAD

**Issue by KSXGitHub** [ouuan/AUR-packages#1]
https://github.com/ouuan/AUR-packages/blob/868c1d1f7c08e5217d557f198fb0ac0f96f31056/.github/workflows/push_aur.yml#L36

This means that your CI will break should I make a breaking change. I recommend using [`@v2.1.0`](https://github.com/KSXGitHub/github-actions-deploy-aur/releases/tag/v2.1.0) instead, you can use [dependabot](https://github.com/marketplace/dependabot-preview) if you want to keep the action up-to-date.

**Comment by ouuan** [comment]
I wanted to use the v2 branch, but saw that the v2 branch was "59 commits ahead, 23 commits behind master". Maybe v2.1.0 is a better choice, but I'm wondering why the v2 branch is not updating.

**Comment by KSXGitHub** [comment]
I'm just too lazy to update v2 branch.

**Comment by ouuan** [comment]
> I'm just too lazy to update v2 branch.

Maybe you can use GitHub Actions to update the v2 branch on pushes or on releases.

**Comment by KSXGitHub** [comment]
can you recommend which one?

**Comment by ouuan** [comment]
> can you recommend which one?

https://github.com/ad-m/github-push-action
